name: v5
recipe: lemp
config:
  webroot: docs
  database: mariadb
services:
  node:
    type: node
    globals:
      requirejs: latest
      grunt-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  grunt:
    service: node